 
 /*------------------------------------------------------------------------
    File        : BaseClass
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronco
    Created     : Wed Jul 08 17:55:29 CEST 2020
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

block-level on error undo, throw.

class test.BaseClass: 

end class.