 
 /*------------------------------------------------------------------------
    File        : TestClass2
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronco
    Created     : Mon Jun 08 18:41:36 CEST 2020
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

block-level on error undo, throw.

class test.TestClass2: 

    /*------------------------------------------------------------------------------
     Purpose:
     Notes:
    ------------------------------------------------------------------------------*/

    constructor public TestClass2 (  ):
        
    end constructor.

end class.