 
 /*------------------------------------------------------------------------
    File        : TestClass4
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronco
    Created     : Mon Jun 08 18:42:06 CEST 2020
    Notes       : 
  ----------------------------------------------------------------------*/


using test.BaseClass from propath.

block-level on error undo, throw.

class test.TestClass4 inherits BaseClass: 

    /*------------------------------------------------------------------------------
     Purpose:
     Notes:
    ------------------------------------------------------------------------------*/

    constructor public TestClass4 (  ):
               
    end constructor.

end class.