 
 /*------------------------------------------------------------------------
    File        : TestClass1
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronco
    Created     : Mon Jun 08 18:41:01 CEST 2020
    Notes       : 
  ----------------------------------------------------------------------*/

using test.BaseClass from propath.

block-level on error undo, throw.

class test.TestClass1 inherits BaseClass: 
    
    constructor public TestClass1():
    
    end.
    
end class.
