 
 /*------------------------------------------------------------------------
    File        : TestClass3
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronco
    Created     : Mon Jun 08 18:41:54 CEST 2020
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

block-level on error undo, throw.

class test.TestClass3: 

    /*------------------------------------------------------------------------------
     Purpose:
     Notes:
    ------------------------------------------------------------------------------*/

    constructor public TestClass3 (  ):
             
    end constructor.

end class.